# Proyecto Final Fase 2

##### Héctor Evelio Fajardo Jiménez 18001842
##### Ana Marcela Bethancourt Vargas 09000253

In [93]:
# Instalación de paquetes
# pip install scikit-learn xgboost lightgbm

In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [115]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [116]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [117]:
#from sklearn.naive_bayes import GaussianNB
#from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from datetime import datetime

In [118]:
datapf1 = pd.read_csv("datapf1.csv")
datapf1.head()

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 37 columns]

In [119]:
# Separar (X) y (y)
X = datapf1.drop('Target', axis=1)
y = datapf1['Target']

In [120]:
# Convertir clases a valores numéricos
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Identificar las columnas categóricas y numéricas
categorical_features = X.select_dtypes(include=['object']).columns
numeric_features = X.select_dtypes(include=['number']).columns

# Proceso para características numéricas
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Proceso para características categóricas
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Crear el preprocesador
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Dividir los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ajustar y transformar los datos
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

print("Preprocesamiento completado.")


Preprocesamiento completado.


#### Guardar en CSV

In [90]:
# Transformar todo el dataset para guardarlo
# X_transformed = preprocessor.transform(X)

# Convertir el array transformado a un DataFrame
#X_transformed_df = pd.DataFrame(X_transformed, columns=np.append(numeric_features, preprocessor.named_transformers_['cat']['onehot'].get_feature_names_out(categorical_features)))
#X_transformed_df['Target'] = y

# Guardar el DataFrame transformado a un archivo CSV
#X_transformed_df.to_csv('transformed_datapf1.csv', index=False)


## Naive Bayes

In [121]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Entrenar el modelo
nb = GaussianNB()
nb.fit(X_train, y_train)

# Hacer predicciones
y_pred = nb.predict(X_test)

# Evaluar el modelo
print("Naive Bayes")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Naive Bayes
[[216  34  66]
 [ 28  38  85]
 [ 24  35 359]]
              precision    recall  f1-score   support

           0       0.81      0.68      0.74       316
           1       0.36      0.25      0.29       151
           2       0.70      0.86      0.77       418

    accuracy                           0.69       885
   macro avg       0.62      0.60      0.60       885
weighted avg       0.68      0.69      0.68       885



## b. LDA

In [122]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Entrenar el modelo
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

# Diccionario para almacenar los resultados
results = {'Model': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1-Score': []}

# Hacer predicciones
y_pred = lda.predict(X_test)

# Evaluar el modelo
print("Análisis Discriminante Lineal (LDA)")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Añadir los resultados al diccionario
results['Model'].append('LDA')
results['Accuracy'].append(accuracy_score(y_test, y_pred))
results['Precision'].append(np.mean(classification_report(y_test, y_pred, output_dict=True)['weighted avg']['precision']))
results['Recall'].append(np.mean(classification_report(y_test, y_pred, output_dict=True)['weighted avg']['recall']))
results['F1-Score'].append(np.mean(classification_report(y_test, y_pred, output_dict=True)['weighted avg']['f1-score']))

Análisis Discriminante Lineal (LDA)
[[217  43  56]
 [ 25  51  75]
 [  4  29 385]]
              precision    recall  f1-score   support

           0       0.88      0.69      0.77       316
           1       0.41      0.34      0.37       151
           2       0.75      0.92      0.82       418

    accuracy                           0.74       885
   macro avg       0.68      0.65      0.66       885
weighted avg       0.74      0.74      0.73       885



## c. Regresión Logística

In [123]:
from sklearn.linear_model import LogisticRegression

# Entrenar el modelo
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

# Hacer predicciones
y_pred = log_reg.predict(X_test)

# Evaluar el modelo
print("Regresión Logística")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Regresión Logística
[[244  27  45]
 [ 35  42  74]
 [ 14  24 380]]
              precision    recall  f1-score   support

           0       0.83      0.77      0.80       316
           1       0.45      0.28      0.34       151
           2       0.76      0.91      0.83       418

    accuracy                           0.75       885
   macro avg       0.68      0.65      0.66       885
weighted avg       0.73      0.75      0.74       885



## d. SVM.

In [124]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Entrenar el modelo
svm = SVC()
svm.fit(X_train, y_train)

# Hacer predicciones
y_pred = svm.predict(X_test)

# Evaluar el modelo
print("SVM")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

SVM
[[230  34  52]
 [ 23  48  80]
 [  7  18 393]]
              precision    recall  f1-score   support

           0       0.88      0.73      0.80       316
           1       0.48      0.32      0.38       151
           2       0.75      0.94      0.83       418

    accuracy                           0.76       885
   macro avg       0.70      0.66      0.67       885
weighted avg       0.75      0.76      0.74       885



## e. Árboles de decisión

In [125]:
from sklearn.tree import DecisionTreeClassifier

# Entrenar el modelo
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

# Hacer predicciones
y_pred = dt.predict(X_test)

# Evaluar el modelo
print("Árboles de Decisión")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Árboles de Decisión
[[202  62  52]
 [ 33  61  57]
 [ 36  47 335]]
              precision    recall  f1-score   support

           0       0.75      0.64      0.69       316
           1       0.36      0.40      0.38       151
           2       0.75      0.80      0.78       418

    accuracy                           0.68       885
   macro avg       0.62      0.61      0.62       885
weighted avg       0.68      0.68      0.68       885



## f. Random forest

In [126]:
from sklearn.ensemble import RandomForestClassifier

# Entrenar el modelo
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

# Hacer predicciones
y_pred = rf.predict(X_test)

# Evaluar el modelo
print("Random Forest")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Random Forest
[[247  22  47]
 [ 35  50  66]
 [  8  20 390]]
              precision    recall  f1-score   support

           0       0.85      0.78      0.82       316
           1       0.54      0.33      0.41       151
           2       0.78      0.93      0.85       418

    accuracy                           0.78       885
   macro avg       0.72      0.68      0.69       885
weighted avg       0.76      0.78      0.76       885



## g. Análisis de discriminante lineal

In [42]:
# LDA es el B

## h. Análisis de discriminante cuadrático

In [127]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

# Entrenar el modelo
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)

# Hacer predicciones
y_pred = qda.predict(X_test)

# Evaluar el modelo
print("Análisis de Discriminante Cuadrático")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Análisis de Discriminante Cuadrático
[[222  46  48]
 [ 32  55  64]
 [ 18  46 354]]
              precision    recall  f1-score   support

           0       0.82      0.70      0.76       316
           1       0.37      0.36      0.37       151
           2       0.76      0.85      0.80       418

    accuracy                           0.71       885
   macro avg       0.65      0.64      0.64       885
weighted avg       0.71      0.71      0.71       885



## i. AdaBoost

In [128]:
from sklearn.ensemble import AdaBoostClassifier

# Entrenar el modelo
ada = AdaBoostClassifier()
ada.fit(X_train, y_train)

# Hacer predicciones
y_pred = ada.predict(X_test)

# Evaluar el modelo
print("AdaBoost")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

AdaBoost
[[237  35  44]
 [ 44  41  66]
 [ 19  19 380]]
              precision    recall  f1-score   support

           0       0.79      0.75      0.77       316
           1       0.43      0.27      0.33       151
           2       0.78      0.91      0.84       418

    accuracy                           0.74       885
   macro avg       0.67      0.64      0.65       885
weighted avg       0.72      0.74      0.73       885



## j. Gradient Boosting

In [129]:
from sklearn.ensemble import GradientBoostingClassifier

# Entrenar el modelo
gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

# Hacer predicciones
y_pred = gb.predict(X_test)

# Evaluar el modelo
print("Gradient Boosting")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Gradient Boosting
[[240  31  45]
 [ 39  48  64]
 [  8  24 386]]
              precision    recall  f1-score   support

           0       0.84      0.76      0.80       316
           1       0.47      0.32      0.38       151
           2       0.78      0.92      0.85       418

    accuracy                           0.76       885
   macro avg       0.69      0.67      0.67       885
weighted avg       0.75      0.76      0.75       885



## k. XGBoost

In [130]:
from xgboost import XGBClassifier

# Entrenar el modelo
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

# Hacer predicciones
y_pred = xgb.predict(X_test)

# Evaluar el modelo
print("XGBoost")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

XGBoost
[[236  35  45]
 [ 32  65  54]
 [ 13  25 380]]
              precision    recall  f1-score   support

           0       0.84      0.75      0.79       316
           1       0.52      0.43      0.47       151
           2       0.79      0.91      0.85       418

    accuracy                           0.77       885
   macro avg       0.72      0.70      0.70       885
weighted avg       0.76      0.77      0.76       885



## l. LGBM

In [131]:
from lightgbm import LGBMClassifier

# Entrenar el modelo
lgbm = LGBMClassifier()
lgbm.fit(X_train, y_train)

# Hacer predicciones
y_pred = lgbm.predict(X_test)

# Evaluar el modelo
print("LGBM")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001602 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1300
[LightGBM] [Info] Number of data points in the train set: 3539, number of used features: 36
[LightGBM] [Info] Start training from score -1.163999
[LightGBM] [Info] Start training from score -1.705455
[LightGBM] [Info] Start training from score -0.681070
LGBM
[[237  35  44]
 [ 33  59  59]
 [ 12  24 382]]
              precision    recall  f1-score   support

           0       0.84      0.75      0.79       316
           1       0.50      0.39      0.44       151
           2       0.79      0.91      0.85       418

    accuracy                           0.77       885
   macro avg       0.71      0.68      0.69       885
weighted avg       0.76      0.77      0.76       885



## Evaluación y Comparación de los Modelos

In [132]:
# Diccionario para almacenar los resultados
results_df = {'Model': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1-Score': []}

# Lista de modelos entrenados
models = [
    ('Naive Bayes', nb),
    ('Regresión Logística', log_reg),
    ('LDA', lda),
    ('SVM', svm),
    ('Árboles de Decisión', dt),
    ('Random Forest', rf),
    ('QDA', qda),
    ('AdaBoost', ada),
    ('Gradient Boosting', gb),
    ('XGBoost', xgb),
    ('LightGBM', lgbm)
]

# Evaluar cada modelo
for name, model in models:
    y_pred = model.predict(X_test)
    results_df['Model'].append(name)
    results_df['Accuracy'].append(accuracy_score(y_test, y_pred))
    results_df['Precision'].append(np.mean(classification_report(y_test, y_pred, output_dict=True)['weighted avg']['precision']))
    results_df['Recall'].append(np.mean(classification_report(y_test, y_pred, output_dict=True)['weighted avg']['recall']))
    results_df['F1-Score'].append(np.mean(classification_report(y_test, y_pred, output_dict=True)['weighted avg']['f1-score']))

print(results_df)

{'Model': ['Naive Bayes', 'Regresión Logística', 'LDA', 'SVM', 'Árboles de Decisión', 'Random Forest', 'QDA', 'AdaBoost', 'Gradient Boosting', 'XGBoost', 'LightGBM'], 'Accuracy': [0.6926553672316385, 0.752542372881356, 0.7378531073446327, 0.7581920903954802, 0.6757062146892655, 0.7762711864406779, 0.7129943502824859, 0.7435028248587571, 0.7615819209039548, 0.7694915254237288, 0.7661016949152543], 'Precision': [0.6808496622313589, 0.7340833505891269, 0.7381215463711595, 0.7513235239336935, 0.6837374816366255, 0.7630570309750271, 0.7140619706576649, 0.7220019054901176, 0.7464128346604858, 0.7633022976849878, 0.757404897248009], 'Recall': [0.6926553672316385, 0.752542372881356, 0.7378531073446327, 0.7581920903954802, 0.6757062146892655, 0.7762711864406779, 0.7129943502824859, 0.7435028248587571, 0.7615819209039548, 0.7694915254237288, 0.7661016949152543], 'F1-Score': [0.6798231949956989, 0.7363081777186452, 0.728637291494608, 0.7440918759181377, 0.6777068015120471, 0.7612924204400309, 0.7

In [ ]:
# Lo mismo de aqui arriba pero lo guarda en el CSV

In [133]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from datetime import datetime

# Entrenar y evaluar modelos
models = [
    ('Naive Bayes', GaussianNB()),
    ('Regresión Logística', LogisticRegression(max_iter=1000)),
    ('LDA', LinearDiscriminantAnalysis()),
    ('SVM', SVC()),
    ('Árboles de Decisión', DecisionTreeClassifier()),
    ('Random Forest', RandomForestClassifier()),
    ('QDA', QuadraticDiscriminantAnalysis()),
    ('AdaBoost', AdaBoostClassifier()),
    ('Gradient Boosting', GradientBoostingClassifier()),
    ('XGBoost', XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')),
    ('LightGBM', LGBMClassifier())
]

# Para almacenar los resultados
results_df = {'Model': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1-Score': [], 'Timestamp': []}

# Evaluar cada modelo
for name, model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    
    results_df['Model'].append(name)
    results_df['Accuracy'].append(accuracy_score(y_test, y_pred))
    results_df['Precision'].append(report['weighted avg']['precision'])
    results_df['Recall'].append(report['weighted avg']['recall'])
    results_df['F1-Score'].append(report['weighted avg']['f1-score'])
    results_df['Timestamp'].append(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

# Crear un DataFrame con los resultados
results_df = pd.DataFrame(results_df)

# Ordenar el DataFrame por precisión
results_df = results_df.sort_values(by='Accuracy', ascending=False)

# Guardar los resultados en un archivo CSV
results_df.to_csv('Modelo_evaluacion.csv', index=False)

print("Los resultados se han guardado 'Modelo_evaluacion.csv'.")

print(results_df)

C:\Users\Administrador\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [11:40:08] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-06abd128ca6c1688d-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001381 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1300
[LightGBM] [Info] Number of data points in the train set: 3539, number of used features: 36
[LightGBM] [Info] Start training from score -1.163999
[LightGBM] [Info] Start training from score -1.705455
[LightGBM] [Info] Start training from score -0.681070
Los resultados se han guardado 'Modelo_evaluacion.csv'.
                  Model  Accuracy  Precision    Recall  F1-Score  \
9               XGBoost  0.769492   0.763302  0.769492  0.762844   
10             LightGBM  0.766102   0.757405  0.766102  0.757480   
8     Gradient Boosting  0.764972   0.752242  0.764972  0.752399   
5         Random Forest  0.763842   0.747989  0.763842  0.748452   
3                   SVM  0.758192   0.751324  0.758192  0.744092   
1   Regresión Logístic